version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.13.3
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source:  ./volumn/elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - service
  fluentd:
    image: yowko/fluentd-elasticsearch:1.0.0
    container_name: fluentd
    volumes:
      - type: bind
        source: ./config/fluent.conf
        target: /fluentd/etc/fluent.conf
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
      - "8888:8888"
    networks:
      - service
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.13.3
    container_name: kibana
    volumes:
      - type: bind
        source: ./config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - service
    depends_on:
      - elasticsearch


  metabase-secrets:
    image: metabase/metabase:latest
    container_name: metabase-secrets
    hostname: metabase-secrets
    volumes:
      - ./volumn/metabase-data:/metabase-data      
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - service
    depends_on:
      - postgres-secrets
    secrets:
      - db_password
      - db_user
  postgres-secrets:
    image: postgres:latest
    container_name: postgres-secrets
    hostname: postgres-secrets
    volumes:
      - ./volumn/postgre:/var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - service
    secrets:
      - db_password
      - db_user
  grafana:
    image: grafana/grafana:8.0.6-ubuntu
    ports:
      - 3123:3000
    container_name: grafana
    environment: 
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,frser-sqlite-datasource,petrslavotinek-carpetplot-panel
    networks:
      - service
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
networks:
  service:
    driver: bridge
