requried_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-compose

docker_engines:
  - docker-ce
  - docker-ce-cli
  - containerd.io

user: ntuaha

# https://github.com/docker/compose/releases
docker_compose_version: 1.29.2